INSERT INTO course_data (vocab_id, course_title, week_title, lesson_title, phrases_type, chinese, pinyin, english)
VALUES
(1, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "谁", "shéi", "who, whom"),
(2, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "妈妈", "māmɑ", "mother"),
(3, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "今年", "jīnnián", "this year"),
(4, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "这个", "zhèɡe", "this one"),
(5, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "爸爸", "bàbɑ", "father"),
(6, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "哥哥", "ɡēɡe", "older brother"),
(7, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "妹妹", "mèimei", "younger sister"),
(8, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "vocabulary", "漂亮", "piàoliɑnɡ", "pretty, beautiful"),
(9, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "旭东，她是谁？", "Xùdōng, tā shì shéi?", "Xudong, who is she?"),
(10, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "她是我妈妈。她今年四十六岁。", "Tā shì wǒ māmɑ. Tā jīnnián sìshí liù suì.", "She is my mom. She is 46 years old this year."),
(11, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "她是谁？", "Tā shì shéi?", "Who is she?"),
(12, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "她是我妹妹。她今年十九岁。", "Tā shì wǒ mèimei. Tā jīnnián shíjiǔ suì.", "She is my younger sister. She is 19 years old this year."),
(13, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "你妹妹很漂亮。", "Nǐ mèimei hěn piàoliɑnɡ.", "Your younger sister is very pretty."),
(14, "hsk1", "Greetings and numbers", "L1 你好 Nǐ hǎo!", "dialogue", "谢谢！", "Xièxie!", "Thanks!"),
(15, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "有", "yǒu", "have"),
(16, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "狗", "ɡǒu", "dog"),
(17, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "吗", "mɑ", "(question mark)"),
(18, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "只", "zhī", "measure word"),
(19, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "了", "le", "a particle"),
(20, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "没有", "méiyǒu", "do not have"),
(21, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "猫", "māo", "cat"),
(22, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "汪汪", "Wānɡwàng", "a dog\'s name"),
(23, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "小", "xiǎo", "small"),
(24, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "vocabulary", "喵喵", "Miāomiāo", "a cat\'s name"),
(25, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "旭东，你有狗吗？", "Xùdōng, nǐ yǒu ɡǒu mɑ?", "Xudong, do you have a dog?"),
(26, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "有。我有一只大狗。", "Yǒu. Wǒ yǒu yì zhī dà ɡǒu.", "Yes. I have a big dog."),
(27, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "你的狗多大了？", "Nǐ de ɡǒu duō dà le?", "How old is your dog?"),
(28, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "七岁了。小蓓，你有狗吗？", "Qī suì le. Xiǎobèi, nǐ yǒu ɡǒu mɑ?", "Seven years old. Xiaobei, do you have a dog?"),
(29, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "我没有狗。我有一只三岁的小猫。", "Wǒ méiyǒu ɡǒu. Wǒ yǒu yì zhī sān suì de xiǎo māo.", "No, I don\'t have a dog. I have a 3-year-old kitten."),
(30, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "我的大狗叫汪汪。", "Wǒ de dà ɡǒu jiào Wānɡwàng.", "My dog is called Wangwang."),
(31, "hsk1", "Greetings and numbers", "L2 你是哪国人 Nǐ shì nǎ guó rén?", "dialogue", "我的小猫叫喵喵。", "Wǒ de xiǎo māo jiào Miāomiāo.", "My kitten is called Miaomiao."),
(32, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "在", "zài", "to be at/in/on; Indicating location"),
(33, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "北京", "Běijīng", "Beijing"),
(34, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "学习", "xuéxí", "study"),
(35, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "汉语", "hànyǔ", "Chinese"),
(36, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "呢", "ne", "a modal particle"),
(37, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "学校", "xuéxiào", "school"),
(38, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "个", "ɡè", "(measure word)"),
(39, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "儿子", "érzi", "son"),
(40, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "和", "hé", "and"),
(41, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "vocabulary", "女儿", "nǚér", "daughter"),
(42, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "你好！我在北京学习汉语呢！", "Nǐ hǎo! Wǒ zài Běijīng xuéxí hànyǔ ne!", "Hello! I am learning Chinese in Beijing."),
(43, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "我们的学校很大。", "Wǒmen de xuéxiào hěn dà.", "Our school is very big."),
(44, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "我的老师叫王欢，她今年三十六岁。", "Wǒ de lǎoshī jiào Wánɡ Huān, Tā jīnnián sān shí liù suì.", "My teacher\'s name is Wang Huan. She is 36 years old this year."),
(45, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "王老师有一个儿子和一个女儿。", "Wánɡ Lǎoshī yǒu yí gè érzi hé yí gè nǚ’ér.", "Teacher Wang has a son and a daughter."),
(46, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "她儿子五岁，女儿三岁。", "Tā érzi wǔ suì, nǚ\'ér sān suì.", "Her son is 5, and her daughter is 3."),
(47, "hsk1", "Greetings and numbers", "L3 你多大了 Nǐ duō dà le？", "dialogue", "你怎么样？", "Nǐ zěnmeyànɡ?", "How about you?"),
(48, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "朋友", "pénɡyou", "friend"),
(49, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "看", "kàn", "watch"),
(50, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "电影", "diànyǐnɡ", "movie"),
(51, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "你们", "nǐmen", "you all"),
(52, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "今天", "jīntiān", "today"),
(53, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "想", "xiǎnɡ", "want"),
(54, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "功夫", "ɡōnɡfu", "kungfu"),
(55, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "vocabulary", "熊猫", "xiónɡmāo", "panda"),
(56, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "他是你的同学吗？", "Tā shì nǐ de tóngxué mɑ?", "Is he your classmate?"),
(57, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "是。我们认识三年了。", "Shì. Wǒmen rènshí sān nián le.", "Yes, we have known each other for 3 years."),
(58, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "她也是你的同学吗？", "Tā yě shì nǐ de tóngxué mɑ?", "Is she also your classmate?"),
(59, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "不是。她是我的朋友，我们一起看电影。", "Bú shì. Tā shì wǒ de pénɡyou, wǒmen yìqǐ kàn diànyǐnɡ.", "No, she is my friend. We watch movies together."),
(60, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "你们今天想看电影吗？", "Nǐmen jīntiān xiǎnɡ kàn diànyǐnɡ mɑ?", "Do you want to watch a movie today?"),
(61, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "想看呀！我们想看《功夫熊猫》。", "Xiǎnɡ kàn ya! Wǒmen xiǎnɡ kàn Gōnɡfu Xiónɡmāo.", "Yes, I want to. We want to watch Kung Fu Panda."),
(62, "hsk1", "Greetings and numbers", "L4 我的电话号码是 Wǒ de diànhuà hàomǎ shì", "dialogue", "看，是这个！", "Kàn, shì zhè ɡe!", "Look, this one!"),
(63, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "老师", "lǎoshī", "teacher"),
(64, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "同学", "tónɡxué", "classmate"),
(65, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "们", "men", "suff. plural indicator for pronouns and a few animate nouns"),
(66, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "怎么样", "zěnmeyànɡ", "is used to ask about the condition of something or someone"),
(67, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "谢谢", "xièxie", "thanks"),
(68, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "不客气", "bú kèqi", "you are welcome"),
(69, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "对不起", "duìbuqǐ", "Sorry"),
(70, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "没关系", "méi ɡuānxi", "Not at all/It doesn\'t matter/That’s all right."),
(71, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "vocabulary", "再见", "zàijiàn", "bye"),
(72, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "同学们好！", "Tóngxué men hǎo!", "Hello, students!"),
(73, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "老师好！", "Lǎoshī hǎo!", "Hello teacher!"),
(74, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "你怎么样？", "Nǐ zěnmeyàng?", "How are you?"),
(75, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "我很好。你呢？", "Wǒ hěn hǎo. Nǐ ne?", "I am fine. And you?"),
(76, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "我也很好。", "Wǒ yě hěn hǎo.", "I am fine too."),
(77, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "谢谢！", "Xièxie!", "Thanks!"),
(78, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "不客气！", "Bú kèqi!", "You are welcome!"),
(79, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "对不起！", "Duìbuqǐ!", "Sorry!"),
(80, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "没关系！", "Méi guānxi!", "Not at all!"),
(81, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "再见！", "Zàijiàn!", "Bye!"),
(82, "hsk1", "Greetings and numbers", "L5 谢谢 Xièxie！", "dialogue", "明天见！", "Míngtiān jiàn!", "See you tomorrow!");
