INSERT INTO course_data (vocab_id, course_title, week_title, lesson_title, phrases_type, chinese, pinyin, english)
VALUES
(83, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '谁', 'shéi', 'who, whom'),
(84, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '妈妈', 'māmɑ', 'mother'),
(85, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '今年', 'jīnnián', 'this year'),
(86, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '这个', 'zhèɡe', 'this one'),
(87, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '爸爸', 'bàbɑ', 'father'),
(88, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '哥哥', 'ɡēɡe', 'older brother'),
(89, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '妹妹', 'mèimei', 'younger sister'),
(90, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'vocabulary', '漂亮', 'piàoliɑnɡ', 'pretty, beautiful'),
(91, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '旭东，她是谁？', 'Xùdōnɡ, tā shì shéi?', 'Xudong, who is she?'),
(92, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '她是我妈妈。她今年四十六岁。', 'Tā shì wǒ māmɑ. Tā jīnnián sì shí liù suì.', 'She is my mum. She is 46 years old this year.'),
(93, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '她是谁？', 'Tā shì shéi?', 'Who is she?'),
(94, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '她是我妹妹。她今年十九岁。', 'Tā shì wǒ mèimei. Tā jīnnián shí jiǔ suì.', 'She is my younger sister. She is 19 years old this year.'),
(95, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '你妹妹很漂亮。', 'Nǐ mèimei hěn piàoliɑnɡ.', 'Your younger sister is very pretty.'),
(96, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '谢谢！', 'Xièxie!', 'Thanks!'),
(97, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '这个人是谁？', 'Zhè ɡe rén shì shéi?', 'Who is this person?'),
(98, 'hsk1', 'Family and school/university', 'Lesson 1 她是谁 Tā shì shéi？Who is she? ', 'dialogue', '这个人是我爸爸。他今年五十岁。', 'Zhè ɡe rén shì wǒ bàbɑ. Tā jīnnián wǔshí suì.', 'This is my dad. He is 50 years old this year.'),

-- Lesson 2 Vocabulary
(99, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '有', 'yǒu', 'have'),
(100, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '狗', 'ɡǒu', 'dog'),
(101, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '吗', 'mɑ', '(question mark)'),
(102, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '只', 'zhī', 'measure word'),
(103, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '了', 'le', 'a particle'),
(104, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '没有', 'méi yǒu', 'do not have'),
(105, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '猫', 'māo', 'cat'),
(106, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '汪汪', 'Wānɡwang', "a dog's name"),
(107, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'vocabulary', '小', 'xiǎo', 'small'),

-- Lesson 2 Dialogue
(108, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '喵喵', 'Miāomiao', "a cat's name"),
(109, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '旭东，你有狗吗？', 'Xùdōnɡ，nǐ yǒu ɡǒu mɑ？', 'Xudong, do you have a dog?'),
(110, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '有。我有一只大狗。', 'Yǒu. Wǒ yǒu yì zhī dà ɡǒu.', 'Yes, I have a big dog.'),
(111, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '你的狗多大了？', 'Nǐ de ɡǒu duō dà le？', 'How old is your dog?'),
(112, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '七岁了。小蓓，你有狗吗？', 'Qī suì le. Xiǎobèi, nǐ yǒu ɡǒu mɑ？', 'It is 7 years old. Xiaobei, do you have a dog?'),
(113, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '我没有狗。我有一只三岁的小猫。', 'Wǒ méiyǒu ɡǒu. Wǒ yǒu yì zhī sān suì de xiǎo māo.', 'I do not have a dog. I have a 3-year-old kitten.'),
(114, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '我的大狗叫汪汪。', 'Wǒ de dà ɡǒu jiào Wānɡwanɡ.', "My big dog's name is Wangwang."),
(115, 'hsk1', 'Family and school/university', 'Lesson 2 我有一只大狗 Wǒ yǒu yì zhī dà ɡǒu I have a big dog', 'dialogue', '我的小猫叫喵喵。', 'Wǒ de xiǎo māo jiào Miāomiao.', "My kitten's name is Miaomiao."),

-- Lesson 3 Vocabulary
(116, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '在', 'zài', 'to be at/in/on; Indicating location'),
(117, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '北京', 'Běijīnɡ', 'Beijing'),
(118, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '学习', 'xuéxí', 'study'),
(119, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '汉语', 'hànyǔ', 'Chinese'),
(120, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '呢', 'ne', 'a modal particle'),
(121, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '学校', 'xuéxiào', 'school'),
(122, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '个', 'ɡè', '(measure word)'),
(123, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '儿子', 'érzi', 'son'),
(124, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '和', 'hé', 'and'),
(125, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师  Wǒ de hànyǔ lǎoshī My Chinese teacher', 'vocabulary', '女儿', 'nǚér', 'daughter'),

-- Lesson 3 Dialogue
(126, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', 'Jenny：你好！我在北京学习汉语呢！', 'Jenny：Nǐ hǎo！Wǒ zài Běijīng xuéxí hànyǔ ne！', 'Jenny: Hello! I am learning Chinese in Beijing.'),
(127, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', '我们的学校很大。', 'Wǒmen de xuéxiào hěn dà.', 'Our school is very big.'),
(128, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', '我的老师叫王欢，她今年三十六岁。', 'Wǒ de lǎoshī jiào Wánɡ Huān，Tā jīnnián sān shí liù suì.', "My teacher's name is Wang Huan. She is 36 years old this year."),
(129, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', '王老师有一个儿子和一个女儿。', 'Wánɡ Lǎoshī yǒu yí gè érzi hé yí gè nǚ’ér.', "Teacher Wang has a son and a daughter."),
(130, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', '她儿子五岁，女儿三岁。', 'Tā érzi wǔ suì,nǚ’ér sān suì.', "Her son is 5 and her daughter is 3."),
(131, 'hsk1', 'Family and school/university', 'Lesson 3 我的汉语老师 Wǒ de hànyǔ lǎoshī My Chinese teacher', 'dialogue', '你怎么样？', 'Nǐ zěnmeyànɡ？', "How about you?"),
-- Lesson 4 Vocabulary
(132, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '弟弟', 'dìdi', 'younger brother'),
(133, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '会', 'huì', 'can'),
(134, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '说', 'shuō', 'to speak, to say'),
(135, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '一点儿', 'yìdiǎnr', 'a little'),
(136, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '酷', 'kù', 'cool'),
(137, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '对', 'duì', 'right, correct'),
(138, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '写', 'xiě', 'to write'),
(139, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '汉字', 'hànzì', 'Chinese character'),
(140, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'vocabulary', '太……了', 'tài … … le', 'too, very'),

-- Lesson 4 Dialogue
(141, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '乔治，你弟弟会说汉语吗？', 'Qiáozhì, nǐ dìdi huì shuō hànyǔ mɑ？', "Qiaozhi, can your brother speak Chinese?"),
(142, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '会说一点儿。他说，会说汉语很酷！', 'Huì shuō yī diǎnr. Tā shuō，huì shuō hànyǔ hěn kù！', "Yes, he can speak a little. He said, speaking Chinese is cool!"),
(143, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '对！太酷了！他会写汉字吗？', 'Duì！Tài kù le！Tā huì xiě hànzì mɑ？', "Yes, it is very cool! Can he write Chinese characters?"),
(144, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '会。他会写二十五个汉字。', 'Huì. Tā huì xiě èr shí wǔ ɡè hànzì.', "Yes, he can. He can write 25 Chinese characters."),
(145, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '你会写汉字吗？', 'Nǐ huì xiě hànzì mɑ？', "Can you write Chinese characters?"),
(146, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '我会读，不会写。', 'Wǒ huì dú， bú huì xiě.', "I can read. I can’t write."),
(147, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '这四个字怎么读？', 'Zhè sì ɡè zì zěnme dú？', "How to read these four characters?"),
(148, 'hsk1', 'Family and school/university', 'Lesson 4 会说汉语很酷！Huì shuō hànyǔ hěn kù! Speaking Chinese is cool!', 'dialogue', '“北京大学”。', '“Běijīnɡ dàxué”。', "Peking University."),
-- Lesson 5 Vocabulary
(149, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '朋友', 'péngyǒu', 'friend'),
(150, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '看', 'kàn', 'watch'),
(151, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '电影', 'diànyǐng', 'movie'),
(152, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '你们', 'nǐ men', 'you all'),
(153, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '今天', 'jīntiān', 'today'),
(154, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '想', 'xiǎng', 'want'),
(155, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '功夫', 'gōngfu', 'kungfu'),
(156, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'vocabulary', '熊猫', 'xiónɡmāo', 'panda'),
-- Lesson 5 Dialogue
(157, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '他是你的同学吗？', 'Tā shì nǐ de tónɡxué mɑ？', "Is he your classmate?"),
(158, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '是。我们认识三年了。', 'Shì. Wǒmen rènshi sān nián le.', "Yes, we have known each other for 3 years."),
(159, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '她也是你的同学吗？', 'Tā yě shì nǐ de tónɡxué mɑ？', "Is she also your classmate?"),
(160, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '不是。她是我的朋友(friend)，', 'Bú shì. Tā shì wǒ de péngyou，', "No, she is my friend,"),
(161, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '我们一起(together)看电影(film)。', 'wǒ men yì qǐ kàn diànyǐnɡ.', "we watch films together."),
(162, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '你们今天(today)想(would like)看电影吗？', 'Nǐ men jīntiān xiǎnɡ kàn diànyǐnɡ mɑ？', "Do you want to watch a film today?"),
(163, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '想看呀(modal particle)！', 'Xiǎnɡ kàn ya!', "Yes, I want to."),
(164, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '我们想看《功夫熊猫》(Kung Fu Panda)。', 'Wǒmen xiǎnɡ kàn Gōnɡfu Xiónɡmāo.', "We would like to watch Kung Fu Panda."),
(165, 'hsk1', 'Family and school/university', 'Lesson 5 他是你的同学吗 Tā shì nǐ de tónɡxué mɑ？Is he your classmate?', 'dialogue', '看，是这个！', 'Kàn, shì zhè ɡe！', "See, here it is!");